### ISSUE TITLE
你这项目为什么都不考虑并发情况的？很多地方都不加锁，你测试过没数据竞争的情况吗？

### ISSUE THREAD

**Issue by AnkoGo123** [sonhineboy/gsadmin#2]
如题

**Comment by AnkoGo123** [comment]
虽然我没测，但是我看代码发现你几乎都不考虑并发情况的，所以希望后续补上。否则真的只是玩玩的项目罢了

**Comment by sonhineboy** [comment]
感谢提醒。

**Comment by sonhineboy** [comment]
目前全局对象使用是需要在content 上下文中使用，不会造成数据竞争，目前纯在数据更新方面没有使用事务，目前最您版本已经更新.

**Comment by AnkoGo123** [comment]
> 

会造成的，跟content没有任何关系，亲你得好好提升下计算机基础知识~~~

**Comment by AnkoGo123** [comment]
好像我发现你几乎都是使用的非指针的方式来定义方法，我很疑惑到底是什么原因迫使这样做

**Comment by AnkoGo123** [comment]
我猜测你应该是初学go不久？

**Comment by sonhineboy** [comment]
一直在学习中

**Comment by sonhineboy** [comment]
> 好像我发现你几乎都是使用的非指针的方式来定义方法，我很疑惑到底是什么原因迫使这样做

一下子弄不太明白指针，都定义成指针方法怕出现引用地狱（当然出现这个问题和个人能力有关）后期会考虑改正
