### ISSUE TITLE
访问后端api404

### ISSUE THREAD

**Issue by qgmac** [sonhineboy/gsadmin#3]
访问后端API会出现404，验证码和登录接口都会，查看了访问日志发现再api后面多了个空格
![微信截图_20240508095633](https://github.com/sonhineboy/gsadmin/assets/38558055/09dd455a-af57-4415-a417-d4f97a2312f1)

**Comment by sonhineboy** [comment]
我查看仓库里的代码时正常的，没有空格，https://github.com/sonhineboy/gsadmin/blob/09072d755974a4185e7a85324b8ab164274eb628/service/router/router.go#L15C2-L19C1

**Comment by sonhineboy** [comment]
代码实际并没有出现空格，你可以检查下自己的代码或者更新到最新版本。
这个是实际代码：https://github.com/sonhineboy/gsadmin/blob/09072d755974a4185e7a85324b8ab164274eb628/service/router/router.go#L13
可以排查下是否其它地方引起的。
另外我在开发的过工程中并没有出现你说的情况
